version: '3.8'

services:
  todo-mysql:
    image: mysql:latest
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: todo-mysql
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    networks:
      - todo-net

  todo-api:
    image: todo-api
    container_name: todo-api
    ports:
      - "8082:8082"
    networks:
      - todo-net
    depends_on:
      - todo-mysql

networks:
  todo-net:
    driver: bridge