version: '3.8'

services:
  todo-mysql:
    image: mysql:latest
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: todo-mysql
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - todo-net

  todo-api:
    image: todo-api
    container_name: todo-api
    ports:
      - "8082:8082"
    networks:
      - todo-net
    depends_on:
      todo-mysql:
        condition: service_healthy

networks:
  todo-net:
    driver: bridge